// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHNyvikOXKu_U3saZ8VWPzr1qC-Poq8eY',
    appId: '1:960859675190:web:939c4d180af1687a885697',
    messagingSenderId: '960859675190',
    projectId: 'music-app-9a55d',
    authDomain: 'music-app-9a55d.firebaseapp.com',
    storageBucket: 'music-app-9a55d.firebasestorage.app',
    measurementId: 'G-21MGZ9J460',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPC_sIHmlsAB2gy0ADxeTqw0r27dBq1U',
    appId: '1:960859675190:android:d5ca65ed4dd252a6885697',
    messagingSenderId: '960859675190',
    projectId: 'music-app-9a55d',
    storageBucket: 'music-app-9a55d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiAHE1y3CM81ktphRDrchp8OnMXbBAw18',
    appId: '1:960859675190:ios:644060c2047653c9885697',
    messagingSenderId: '960859675190',
    projectId: 'music-app-9a55d',
    storageBucket: 'music-app-9a55d.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiAHE1y3CM81ktphRDrchp8OnMXbBAw18',
    appId: '1:960859675190:ios:644060c2047653c9885697',
    messagingSenderId: '960859675190',
    projectId: 'music-app-9a55d',
    storageBucket: 'music-app-9a55d.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHNyvikOXKu_U3saZ8VWPzr1qC-Poq8eY',
    appId: '1:960859675190:web:65eb0848a68eb037885697',
    messagingSenderId: '960859675190',
    projectId: 'music-app-9a55d',
    authDomain: 'music-app-9a55d.firebaseapp.com',
    storageBucket: 'music-app-9a55d.firebasestorage.app',
    measurementId: 'G-KF7LYY5CFW',
  );
}
